[build]
  # This tells Netlify which folder contains your finished site.
  # Since your HTML files are at the root, we just use "."
  publish = "."

# This is the magic part. This rule tells Netlify how to handle routes.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200